const colors = [
  { value: "white", en: "White", ar: "أبيض", hex: "#FFFFFF" },
  { value: "black", en: "Black", ar: "أسود", hex: "#000000" },
  { value: "gray", en: "Gray", ar: "رمادي", hex: "#808080" },
  { value: "silver", en: "Silver", ar: "فضي", hex: "#C0C0C0" },
  { value: "beige", en: "Beige", ar: "بيج", hex: "#F5F5DC" },
  { value: "ivory", en: "Ivory", ar: "عاجي", hex: "#FFFFF0" },
  { value: "brown", en: "Brown", ar: "بني", hex: "#8B4513" },
  { value: "tan", en: "Tan", ar: "بيج غامق", hex: "#D2B48C" },
  { value: "gold", en: "Gold", ar: "ذهبي", hex: "#FFD700" },
  { value: "red", en: "Red", ar: "أحمر", hex: "#FF0000" },
  { value: "crimson", en: "Crimson", ar: "أحمر غامق", hex: "#DC143C" },
  { value: "maroon", en: "Maroon", ar: "كستنائي", hex: "#800000" },
  { value: "pink", en: "Pink", ar: "وردي", hex: "#FFC0CB" },
  { value: "hotpink", en: "Hot Pink", ar: "وردي غامق", hex: "#FF69B4" },
  { value: "lightpink", en: "Light Pink", ar: "وردي فاتح", hex: "#FFB6C1" },
  { value: "peach", en: "Peach", ar: "خوخي", hex: "#FFDAB9" },
  { value: "coral", en: "Coral", ar: "مرجاني", hex: "#FF7F50" },
  { value: "salmon", en: "Salmon", ar: "سلمون", hex: "#FA8072" },
  { value: "orange", en: "Orange", ar: "برتقالي", hex: "#FFA500" },
  { value: "yellow", en: "Yellow", ar: "أصفر", hex: "#FFFF00" },
  { value: "cream", en: "Cream", ar: "كريمي", hex: "#FFFDD0" },
  { value: "green", en: "Green", ar: "أخضر", hex: "#008000" },
  { value: "lightgreen", en: "Light Green", ar: "أخضر فاتح", hex: "#90EE90" },
  { value: "darkgreen", en: "Dark Green", ar: "أخضر غامق", hex: "#006400" },
  { value: "olive", en: "Olive", ar: "زيتوني", hex: "#808000" },
  { value: "teal", en: "Teal", ar: "بطي", hex: "#008080" },
  { value: "turquoise", en: "Turquoise", ar: "فيروزي", hex: "#40E0D0" },
  { value: "blue", en: "Blue", ar: "أزرق", hex: "#0000FF" },
  { value: "lightblue", en: "Light Blue", ar: "أزرق فاتح", hex: "#ADD8E6" },
  { value: "darkblue", en: "Dark Blue", ar: "أزرق غامق", hex: "#00008B" },
  { value: "navy", en: "Navy", ar: "كحلي", hex: "#000080" },
  { value: "skyblue", en: "Sky Blue", ar: "أزرق سماوي", hex: "#87CEEB" },
  { value: "royalblue", en: "Royal Blue", ar: "أزرق ملكي", hex: "#4169E1" },
  { value: "purple", en: "Purple", ar: "بنفسجي", hex: "#800080" },
  { value: "lavender", en: "Lavender", ar: "لافندر", hex: "#E6E6FA" },
  { value: "violet", en: "Violet", ar: "بنفسجي فاتح", hex: "#EE82EE" },
  { value: "indigo", en: "Indigo", ar: "نيلي", hex: "#4B0082" },
  { value: "magenta", en: "Magenta", ar: "أرجواني", hex: "#FF00FF" },
  { value: "fuchsia", en: "Fuchsia", ar: "فوشيا", hex: "#FF00FF" },
  { value: "chocolate", en: "Chocolate", ar: "شوكولاتة", hex: "#D2691E" },
  { value: "coffee", en: "Coffee", ar: "قهوة", hex: "#6F4E37" },
  { value: "rose", en: "Rose", ar: "وردي", hex: "#FF007F" },
  { value: "mint", en: "Mint", ar: "نعناعي", hex: "#98FF98" },
  { value: "dustyrose", en: "Dusty Rose", ar: "وردي باهت", hex: "#DCA3A3" },
  { value: "sage", en: "Sage", ar: "أخضر مائل للرمادي", hex: "#BCB88A" },
  { value: "mustard", en: "Mustard", ar: "خردلي", hex: "#FFDB58" },
  { value: "burgundy", en: "Burgundy", ar: "بورجوندي", hex: "#800020" },
  { value: "plum", en: "Plum", ar: "برقوقي", hex: "#DDA0DD" },
  { value: "mauve", en: "Mauve", ar: "أرجواني باهت", hex: "#E0B0FF" },
];

export default colors;
